### ISSUE TITLE
airport导航数据在哪获取啊？

### ISSUE THREAD

**Issue by zy6950** [shinoyasan/Airway-Route-Finder#12]
我查找了navigraph里面没有，请问哪里获取呢？

**Comment by gtxzsxxk** [comment]
airport和nav这两个说法仅局限于本项目，这些airport数据和nav数据，都是使用airbusx_extended_v115这个整体的导航数据处理出来的，所以你只需要去下一个airbusx_extended_v115的导航数据就可以了
