### ISSUE TITLE
without-httpclient branch?

### ISSUE THREAD

**Issue by ghost** [shinoyasan/Airway-Route-Finder#8]
提亿点建议（）
搞一个不带http客户端的分支
把ReadASData分离到packData.py
然后在RTFCALC里加一个__init__来加载navidata和airport（指传参）

**Comment by gtxzsxxk** [comment]
你说的功能我已经有实现，具体代码就藏在webclient.py里边 你可以把他提出来。
但我现在得高考啊 还剩130天 等我出来再详细解决这个吧
你愿意的话也可以直接提个pr来

**Comment by gtxzsxxk** [comment]
你是海南的？

**Comment by ghost** [comment]
不是

**Comment by ghost** [comment]
我山东的

**Comment by gamecss** [comment]
* 头像有点晦气

**Comment by ghost** [comment]
> 你说的功能我已经有实现，具体代码就藏在webclient.py里边 你可以把他提出来。
> 但我现在得高考啊 还剩130天 等我出来再详细解决这个吧
> 你愿意的话也可以直接提个pr来

已经搞好了 #9 
merge一下？(ry

**Comment by ghost** [comment]
* I forget delete orphan file progressbar.py
